### ISSUE TITLE
Mostrar ranking dos jogadores ao comando `/elo`

### ISSUE THREAD

**Issue by JoaoFagundes** [rodrigomellogarcia/TheFutBot#21]
Ao executar o comando `/elo`, o bot poderia mostrar a lista dos jogadores ordenada pelo rank de cada um

**Comment by espindolaa** [comment]
Wasn't this addressed by https://github.com/rodrigomellogarcia/TheFutBot/pull/22?
If so, @JoaoFagundes, can we close this issue?
